/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.diego.tiendaropa2.vista;

import com.diego.tiendaropa2.controlador.ControladorClientes;
import com.diego.tiendaropa2.controlador.ControladorProductos;
import com.diego.tiendaropa2.controlador.ControladorVentas;

/**
 *
 * @author USUARIO
 */
public class VistaPrincipal extends javax.swing.JFrame {
    private ControladorClientes controladorClientes;
    private ControladorProductos controladorProductos;
    private ControladorVentas controladorVentas;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        
        // Inicializar el controlador de clientes con los componentes de la vista
        controladorClientes = new ControladorClientes(
            tblClientes,
            txtClienteCedula,
            txtClienteNombre,
            txtClienteCorreo,
            txtClienteAvisos
        );
        controladorClientes.cargarTablaClientes();
        
        // Inicializar el controlador de productos
        controladorProductos = new ControladorProductos(
            tblProductos,
            txtProductoCodigo,
            txtProductoNombre,
            txtProductoTalla,
            txtProductoColor,
            txtProductoPrecio,
            txtProductoStock,
            txtProductoAvisos
        );
        controladorProductos.cargarTablaProductos();
        
        // Inicializar el controlador de ventas
        controladorVentas = new ControladorVentas(
            comboVentaCliente,
            comboVentaProducto,
            txtVentaCantidad,
            txtVentaFecha,
            txtVentaTotal,
            tblVentaDetalles,
            txtVentaAvisos
        );
        controladorVentas.cargarClientesEnCombo();
        controladorVentas.cargarProductosEnCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMenuNavegacion = new javax.swing.JTabbedPane();
        tabCanal = new javax.swing.JPanel();
        btnClienteAgregar = new javax.swing.JButton();
        btnClienteLimpiar = new javax.swing.JButton();
        btnClienteEliminar = new javax.swing.JButton();
        txtClienteCedula = new javax.swing.JTextField();
        lblClienteCedula = new javax.swing.JLabel();
        txtClienteNombre = new javax.swing.JTextField();
        lblClienteNombre = new javax.swing.JLabel();
        lblClienteCorreo = new javax.swing.JLabel();
        txtClienteCorreo = new javax.swing.JTextField();
        lblClientes = new javax.swing.JLabel();
        lblListadoClientes = new javax.swing.JLabel();
        btnClienteEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        lblClienteAvisosTitulo = new javax.swing.JLabel();
        scrollClientes = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtClienteAvisos = new javax.swing.JTextArea();
        tabProductos = new javax.swing.JPanel();
        txtProductoPrecio = new javax.swing.JTextField();
        lblProductoPrecio = new javax.swing.JLabel();
        lblVistaProductosTitulo = new javax.swing.JLabel();
        txtProductoCodigo = new javax.swing.JTextField();
        lblProductoCodigo = new javax.swing.JLabel();
        txtProductoNombre = new javax.swing.JTextField();
        lblProductoNombre = new javax.swing.JLabel();
        lblProductoTalla = new javax.swing.JLabel();
        txtProductoTalla = new javax.swing.JTextField();
        lblProductoCantidad = new javax.swing.JLabel();
        txtProductoStock = new javax.swing.JTextField();
        lblListadoProductos = new javax.swing.JLabel();
        lblProductoColor = new javax.swing.JLabel();
        txtProductoColor = new javax.swing.JTextField();
        btnProductoAgregar = new javax.swing.JButton();
        btnProductoEditar = new javax.swing.JButton();
        btnProductoEliminar = new javax.swing.JButton();
        btnProductoLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        scrollProductos = new javax.swing.JScrollPane();
        lblProductoAvisosTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProductoAvisos = new javax.swing.JTextArea();
        tabVentas = new javax.swing.JPanel();
        lblVistaVentasTitulo = new javax.swing.JLabel();
        lblVentaCliente = new javax.swing.JLabel();
        lblFechaVenta = new javax.swing.JLabel();
        lblVentaProducto = new javax.swing.JLabel();
        lblVentaCantidad = new javax.swing.JLabel();
        btnVentaAgregar = new javax.swing.JButton();
        comboVentaCliente = new javax.swing.JComboBox<>();
        lblVentaFecha = new javax.swing.JLabel();
        comboVentaProducto = new javax.swing.JComboBox<>();
        txtVentaFecha = new javax.swing.JTextField();
        txtVentaCantidad = new javax.swing.JTextField();
        btnVentaQuitar = new javax.swing.JButton();
        btnVentaRegistrar = new javax.swing.JButton();
        btnVentaLimpiar = new javax.swing.JButton();
        lblListadoVentas = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblVentaDetalles = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        lblVentaTotal = new javax.swing.JLabel();
        txtVentaTotal = new javax.swing.JTextField();
        lblVentaAvisosTitulo = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtVentaAvisos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabMenuNavegacion.setToolTipText("");
        tabMenuNavegacion.setName(""); // NOI18N

        btnClienteAgregar.setText("Agregar");
        btnClienteAgregar.addActionListener(this::btnClienteAgregarActionPerformed);

        btnClienteLimpiar.setText("Limpiar");
        btnClienteLimpiar.addActionListener(this::btnClienteLimpiarActionPerformed);

        btnClienteEliminar.setText("Eliminar");
        btnClienteEliminar.addActionListener(this::btnClienteEliminarActionPerformed);

        lblClienteCedula.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClienteCedula.setText("Cédula:");

        lblClienteNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClienteNombre.setText("Nombre:");

        lblClienteCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClienteCorreo.setText("Correo:");

        lblClientes.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblClientes.setText("Gestion de Clientes");

        lblListadoClientes.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblListadoClientes.setText("Listado Clientes");

        btnClienteEditar.setText("Editar");
        btnClienteEditar.addActionListener(this::btnClienteEditarActionPerformed);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Correo"
            }
        ));
        tblClientes.setColumnSelectionAllowed(true);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);
        tblClientes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblClienteAvisosTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClienteAvisosTitulo.setText("Avisos:");

        txtClienteAvisos.setEditable(false);
        txtClienteAvisos.setColumns(20);
        txtClienteAvisos.setRows(5);
        jScrollPane4.setViewportView(txtClienteAvisos);

        javax.swing.GroupLayout tabCanalLayout = new javax.swing.GroupLayout(tabCanal);
        tabCanal.setLayout(tabCanalLayout);
        tabCanalLayout.setHorizontalGroup(
            tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCanalLayout.createSequentialGroup()
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCanalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabCanalLayout.createSequentialGroup()
                                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblClienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtClienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnClienteAgregar)
                                    .addComponent(btnClienteEditar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnClienteEliminar)
                                    .addComponent(btnClienteLimpiar)))
                            .addComponent(lblListadoClientes)
                            .addGroup(tabCanalLayout.createSequentialGroup()
                                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabCanalLayout.createSequentialGroup()
                                        .addComponent(lblClienteAvisosTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane4))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tabCanalLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblClientes)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        tabCanalLayout.setVerticalGroup(
            tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabCanalLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblClientes)
                .addGap(36, 36, 36)
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClienteCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClienteCedula)
                    .addComponent(btnClienteAgregar)
                    .addComponent(btnClienteEliminar))
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCanalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClienteNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClienteCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClienteCorreo)))
                    .addGroup(tabCanalLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClienteLimpiar)
                            .addComponent(btnClienteEditar))))
                .addGap(51, 51, 51)
                .addComponent(lblListadoClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabCanalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(tabCanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblClienteAvisosTitulo)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(tabCanalLayout.createSequentialGroup()
                        .addComponent(scrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabMenuNavegacion.addTab("Clientes", tabCanal);

        lblProductoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProductoPrecio.setText("Precio:");

        lblVistaProductosTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblVistaProductosTitulo.setText("Gestion de Productos");

        lblProductoCodigo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProductoCodigo.setText("Código:");

        lblProductoNombre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProductoNombre.setText("Nombre:");

        lblProductoTalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProductoTalla.setText("Talla:");

        lblProductoCantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblProductoCantidad.setText("Stock:");

        lblListadoProductos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblListadoProductos.setText("Listado de Productos");

        lblProductoColor.setText("Color:");

        btnProductoAgregar.setText("Agregar");
        btnProductoAgregar.addActionListener(this::btnProductoAgregarActionPerformed);

        btnProductoEditar.setText("Editar");
        btnProductoEditar.addActionListener(this::btnProductoEditarActionPerformed);

        btnProductoEliminar.setText("Eliminar");
        btnProductoEliminar.addActionListener(this::btnProductoEliminarActionPerformed);

        btnProductoLimpiar.setText("Limpiar");
        btnProductoLimpiar.addActionListener(this::btnProductoLimpiarActionPerformed);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Talla", "Color", "Precio", "Stock"
            }
        ));
        tblProductos.setColumnSelectionAllowed(true);
        tblProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblProductos);
        tblProductos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblProductoAvisosTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProductoAvisosTitulo.setText("Avisos:");

        txtProductoAvisos.setEditable(false);
        txtProductoAvisos.setColumns(20);
        txtProductoAvisos.setRows(5);
        jScrollPane2.setViewportView(txtProductoAvisos);

        javax.swing.GroupLayout tabProductosLayout = new javax.swing.GroupLayout(tabProductos);
        tabProductos.setLayout(tabProductosLayout);
        tabProductosLayout.setHorizontalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductosLayout.createSequentialGroup()
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabProductosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblProductoColor)
                                .addComponent(lblProductoTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblProductoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductoCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(tabProductosLayout.createSequentialGroup()
                                .addComponent(txtProductoStock, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(tabProductosLayout.createSequentialGroup()
                                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductoColor, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtProductoTalla, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProductoAgregar)
                                    .addComponent(btnProductoEliminar))
                                .addGap(28, 28, 28)
                                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnProductoEditar)
                                    .addComponent(btnProductoLimpiar)))))
                    .addGroup(tabProductosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListadoProductos)
                            .addGroup(tabProductosLayout.createSequentialGroup()
                                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tabProductosLayout.createSequentialGroup()
                                        .addComponent(lblProductoAvisosTitulo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane2))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabProductosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVistaProductosTitulo)
                .addGap(237, 237, 237))
        );
        tabProductosLayout.setVerticalGroup(
            tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabProductosLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblVistaProductosTitulo)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabProductosLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductoCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductoNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductoTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductoTalla))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductoColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductoColor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductoPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProductoStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductoCantidad)))
                    .addGroup(tabProductosLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProductoAgregar)
                            .addComponent(btnProductoEditar))
                        .addGap(18, 18, 18)
                        .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProductoEliminar)
                            .addComponent(btnProductoLimpiar))))
                .addGap(18, 18, 18)
                .addComponent(lblListadoProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tabProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductoAvisosTitulo)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        tabMenuNavegacion.addTab("Productos", tabProductos);

        lblVistaVentasTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblVistaVentasTitulo.setText("Gestion de Ventas");

        lblVentaCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVentaCliente.setText("Cliente:");

        lblVentaProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVentaProducto.setText("Producto:");

        lblVentaCantidad.setText("Cantidad:");

        btnVentaAgregar.setText("Agregar");
        btnVentaAgregar.addActionListener(this::btnVentaAgregarActionPerformed);

        comboVentaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblVentaFecha.setText("Fecha:");

        comboVentaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtVentaFecha.setEditable(false);

        btnVentaQuitar.setText("Quitar");
        btnVentaQuitar.addActionListener(this::btnVentaQuitarActionPerformed);

        btnVentaRegistrar.setText("Registrar");
        btnVentaRegistrar.addActionListener(this::btnVentaRegistrarActionPerformed);

        btnVentaLimpiar.setText("Limpiar");
        btnVentaLimpiar.addActionListener(this::btnVentaLimpiarActionPerformed);

        lblListadoVentas.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblListadoVentas.setText("Listado de Ventas:");

        tblVentaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Cantidad", "Precio", "Subtotal"
            }
        ));
        tblVentaDetalles.setColumnSelectionAllowed(true);
        jScrollPane5.setViewportView(tblVentaDetalles);
        tblVentaDetalles.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblVentaTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVentaTotal.setText("Total:");

        txtVentaTotal.setEditable(false);
        txtVentaTotal.setText("$0.00");

        lblVentaAvisosTitulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblVentaAvisosTitulo.setText("Avisos:");

        txtVentaAvisos.setEditable(false);
        txtVentaAvisos.setColumns(20);
        txtVentaAvisos.setRows(5);
        jScrollPane7.setViewportView(txtVentaAvisos);

        javax.swing.GroupLayout tabVentasLayout = new javax.swing.GroupLayout(tabVentas);
        tabVentas.setLayout(tabVentasLayout);
        tabVentasLayout.setHorizontalGroup(
            tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabVentasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblVistaVentasTitulo)
                .addGap(255, 255, 255))
            .addGroup(tabVentasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabVentasLayout.createSequentialGroup()
                        .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabVentasLayout.createSequentialGroup()
                                .addComponent(lblVentaTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtVentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(tabVentasLayout.createSequentialGroup()
                        .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabVentasLayout.createSequentialGroup()
                                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(tabVentasLayout.createSequentialGroup()
                                            .addComponent(lblVentaCliente)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(comboVentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(tabVentasLayout.createSequentialGroup()
                                                    .addGap(124, 124, 124)
                                                    .addComponent(lblFechaVenta))
                                                .addGroup(tabVentasLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(lblVentaProducto)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(comboVentaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(tabVentasLayout.createSequentialGroup()
                                            .addComponent(lblVentaCantidad)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtVentaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblVentaFecha)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtVentaFecha)))
                                    .addGroup(tabVentasLayout.createSequentialGroup()
                                        .addComponent(lblListadoVentas)
                                        .addGap(275, 275, 275)))
                                .addGap(58, 58, 58)
                                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnVentaRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVentaAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVentaQuitar)
                                    .addComponent(btnVentaLimpiar)))
                            .addGroup(tabVentasLayout.createSequentialGroup()
                                .addComponent(lblVentaAvisosTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tabVentasLayout.setVerticalGroup(
            tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabVentasLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblVistaVentasTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFechaVenta)
                .addGap(16, 16, 16)
                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVentaCliente)
                    .addComponent(comboVentaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVentaProducto)
                    .addComponent(comboVentaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentaAgregar)
                    .addComponent(btnVentaQuitar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVentaCantidad)
                    .addComponent(txtVentaCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVentaFecha)
                    .addComponent(txtVentaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVentaRegistrar)
                    .addComponent(btnVentaLimpiar))
                .addGap(33, 33, 33)
                .addComponent(lblListadoVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVentaTotal)
                    .addComponent(txtVentaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(tabVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVentaAvisosTitulo)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tabMenuNavegacion.addTab("Ventas", tabVentas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMenuNavegacion)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMenuNavegacion)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // ==================== EVENTOS CLIENTES ====================
    private void btnClienteAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorClientes.agregarCliente();
    }

    private void btnClienteEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorClientes.eliminarCliente();
    }

    private void btnClienteLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorClientes.limpiarCampos();
        controladorClientes.mostrarAviso("");
    }

    private void btnClienteEditarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorClientes.editarCliente();
    }

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {
        controladorClientes.cargarDatosClienteSeleccionado();
    }

    // ==================== EVENTOS PRODUCTOS ====================
    private void btnProductoAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorProductos.agregarProducto();
    }

    private void btnProductoEditarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorProductos.editarProducto();
    }

    private void btnProductoEliminarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorProductos.eliminarProducto();
    }

    private void btnProductoLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorProductos.limpiarCampos();
        controladorProductos.mostrarAviso("");
    }

    private void tblProductosMouseClicked(java.awt.event.MouseEvent evt) {
        controladorProductos.cargarDatosProductoSeleccionado();
    }

    // ==================== EVENTOS VENTAS ====================
    private void btnVentaAgregarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorVentas.agregarProductoAlCarrito();
    }

    private void btnVentaQuitarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorVentas.quitarProductoDelCarrito();
    }

    private void btnVentaRegistrarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorVentas.registrarVenta();
    }

    private void btnVentaLimpiarActionPerformed(java.awt.event.ActionEvent evt) {
        controladorVentas.limpiarCarrito();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteAgregar;
    private javax.swing.JButton btnClienteEditar;
    private javax.swing.JButton btnClienteEliminar;
    private javax.swing.JButton btnClienteLimpiar;
    private javax.swing.JButton btnProductoAgregar;
    private javax.swing.JButton btnProductoEditar;
    private javax.swing.JButton btnProductoEliminar;
    private javax.swing.JButton btnProductoLimpiar;
    private javax.swing.JButton btnVentaAgregar;
    private javax.swing.JButton btnVentaLimpiar;
    private javax.swing.JButton btnVentaQuitar;
    private javax.swing.JButton btnVentaRegistrar;
    private javax.swing.JComboBox<String> comboVentaCliente;
    private javax.swing.JComboBox<String> comboVentaProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblClienteAvisosTitulo;
    private javax.swing.JLabel lblClienteCedula;
    private javax.swing.JLabel lblClienteCorreo;
    private javax.swing.JLabel lblClienteNombre;
    private javax.swing.JLabel lblClientes;
    private javax.swing.JLabel lblFechaVenta;
    private javax.swing.JLabel lblListadoClientes;
    private javax.swing.JLabel lblListadoProductos;
    private javax.swing.JLabel lblListadoVentas;
    private javax.swing.JLabel lblProductoAvisosTitulo;
    private javax.swing.JLabel lblProductoCantidad;
    private javax.swing.JLabel lblProductoCodigo;
    private javax.swing.JLabel lblProductoColor;
    private javax.swing.JLabel lblProductoNombre;
    private javax.swing.JLabel lblProductoPrecio;
    private javax.swing.JLabel lblProductoTalla;
    private javax.swing.JLabel lblVentaAvisosTitulo;
    private javax.swing.JLabel lblVentaCantidad;
    private javax.swing.JLabel lblVentaCliente;
    private javax.swing.JLabel lblVentaFecha;
    private javax.swing.JLabel lblVentaProducto;
    private javax.swing.JLabel lblVentaTotal;
    private javax.swing.JLabel lblVistaProductosTitulo;
    private javax.swing.JLabel lblVistaVentasTitulo;
    private javax.swing.JScrollPane scrollClientes;
    private javax.swing.JScrollPane scrollProductos;
    private javax.swing.JPanel tabCanal;
    private javax.swing.JTabbedPane tabMenuNavegacion;
    private javax.swing.JPanel tabProductos;
    private javax.swing.JPanel tabVentas;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblVentaDetalles;
    private javax.swing.JTextArea txtClienteAvisos;
    private javax.swing.JTextField txtClienteCedula;
    private javax.swing.JTextField txtClienteCorreo;
    private javax.swing.JTextField txtClienteNombre;
    private javax.swing.JTextArea txtProductoAvisos;
    private javax.swing.JTextField txtProductoCodigo;
    private javax.swing.JTextField txtProductoColor;
    private javax.swing.JTextField txtProductoNombre;
    private javax.swing.JTextField txtProductoPrecio;
    private javax.swing.JTextField txtProductoStock;
    private javax.swing.JTextField txtProductoTalla;
    private javax.swing.JTextArea txtVentaAvisos;
    private javax.swing.JTextField txtVentaCantidad;
    private javax.swing.JTextField txtVentaFecha;
    private javax.swing.JTextField txtVentaTotal;
    // End of variables declaration//GEN-END:variables
}